//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StaticValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRP.App_GlobalResources.StaticValues", typeof(StaticValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indexedControl.
        /// </summary>
        internal static string Class_indexedControl {
            get {
                return ResourceManager.GetString("Class_indexedControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreditCard.
        /// </summary>
        internal static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenId.
        /// </summary>
        internal static string OpenId {
            get {
                return ResourceManager.GetString("OpenId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        internal static string QuestionSet_ContactInformation {
            get {
                return ResourceManager.GetString("QuestionSet_ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmountTotal.
        /// </summary>
        internal static string Report_AmountTotal {
            get {
                return ResourceManager.GetString("Report_AmountTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks_Amount.
        /// </summary>
        internal static string Report_Checks_Amount {
            get {
                return ResourceManager.GetString("Report_Checks_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks_CheckNumber.
        /// </summary>
        internal static string Report_Checks_CheckNumber {
            get {
                return ResourceManager.GetString("Report_Checks_CheckNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks_DateReceived.
        /// </summary>
        internal static string Report_Checks_DateReceived {
            get {
                return ResourceManager.GetString("Report_Checks_DateReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks_Notes.
        /// </summary>
        internal static string Report_Checks_Notes {
            get {
                return ResourceManager.GetString("Report_Checks_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks_Payee.
        /// </summary>
        internal static string Report_Checks_Payee {
            get {
                return ResourceManager.GetString("Report_Checks_Payee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks_TransactionId.
        /// </summary>
        internal static string Report_Checks_TransactionId {
            get {
                return ResourceManager.GetString("Report_Checks_TransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DonationTotal.
        /// </summary>
        internal static string Report_DonationTotal {
            get {
                return ResourceManager.GetString("Report_DonationTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string Report_Paid {
            get {
                return ResourceManager.GetString("Report_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentType.
        /// </summary>
        internal static string Report_PaymentType {
            get {
                return ResourceManager.GetString("Report_PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Report_Quantity {
            get {
                return ResourceManager.GetString("Report_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Report_Total {
            get {
                return ResourceManager.GetString("Report_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks.
        /// </summary>
        internal static string Tab_Checks {
            get {
                return ResourceManager.GetString("Tab_Checks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupons.
        /// </summary>
        internal static string Tab_Coupons {
            get {
                return ResourceManager.GetString("Tab_Coupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Tab_Details {
            get {
                return ResourceManager.GetString("Tab_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editors.
        /// </summary>
        internal static string Tab_Editors {
            get {
                return ResourceManager.GetString("Tab_Editors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        internal static string Tab_Questions {
            get {
                return ResourceManager.GetString("Tab_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Tab_Reports {
            get {
                return ResourceManager.GetString("Tab_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string Tab_Templates {
            get {
                return ResourceManager.GetString("Tab_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string Tab_Transactions {
            get {
                return ResourceManager.GetString("Tab_Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Shared/PageHeader.ascx.
        /// </summary>
        internal static string View_PageHeader {
            get {
                return ResourceManager.GetString("View_PageHeader", resourceCulture);
            }
        }
    }
}
