CREATE TABLE [dbo].[Transactions] (
    [id]                INT              IDENTITY (1, 1) NOT NULL,
    [ItemId]            INT              NOT NULL,
    [TransactionDate]   DATETIME         NOT NULL,
    [IsActive]          BIT              CONSTRAINT [DF_Transactions_IsActive] DEFAULT ((1)) NOT NULL,
    [Credit]            BIT              CONSTRAINT [DF_Transactions_Credit] DEFAULT ((0)) NOT NULL,
    [Check]             BIT              CONSTRAINT [DF_Transactions_Check] DEFAULT ((0)) NOT NULL,
    [Amount]            MONEY            NOT NULL,
    [Donation]          BIT              CONSTRAINT [DF_Transactions_Donation] DEFAULT ((0)) NOT NULL,
    [CouponId]          INT              NULL,
    [TransactionId]     INT              NULL,
    [Quantity]          INT              CONSTRAINT [DF_Transactions_Quantity] DEFAULT ((0)) NOT NULL,
    [TransactionNumber] AS               ([dbo].[udf_GenerateTransactionNumber](datepart(year,[transactiondate]),[id])),
    [OpenIdUserId]      VARCHAR (255)    NULL,
    [ReferenceNumber]   INT              NULL,
    [TrackingId]        INT              NULL,
    [CreatedBy]         VARCHAR (50)     NULL,
    [CorrectionReason]  VARCHAR (MAX)    NULL,
    [TransactionGuid]   UNIQUEIDENTIFIER NULL,
    [Refunded]          BIT              CONSTRAINT [DF_Transactions_Refunded] DEFAULT ((0)) NOT NULL,
    [Notified]          BIT              CONSTRAINT [DF_Transactions_Notified] DEFAULT ((0)) NOT NULL,
    [NotifiedDate]      DATETIME         NULL,
    [FidUsed]           VARCHAR (3)      NULL,
    CONSTRAINT [PK_Transactions] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_Transactions_Coupons] FOREIGN KEY ([CouponId]) REFERENCES [dbo].[Coupons] ([id]),
    CONSTRAINT [FK_Transactions_Items] FOREIGN KEY ([ItemId]) REFERENCES [dbo].[Items] ([id]),
    CONSTRAINT [FK_Transactions_OpenIdUsers] FOREIGN KEY ([OpenIdUserId]) REFERENCES [dbo].[OpenIdUsers] ([id]),
    CONSTRAINT [FK_Transactions_Transactions] FOREIGN KEY ([TransactionId]) REFERENCES [dbo].[Transactions] ([id])
);

