//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRP.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRP.Core.Resources.NotificationMessages", typeof(NotificationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ObjectType}.
        /// </summary>
        public static string ObjectType {
            get {
                return ResourceManager.GetString("ObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ObjectType} has been activated..
        /// </summary>
        public static string STR_Activated {
            get {
                return ResourceManager.GetString("STR_Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ObjectType} has been deactivated..
        /// </summary>
        public static string STR_Deactivated {
            get {
                return ResourceManager.GetString("STR_Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor already attached to that item..
        /// </summary>
        public static string STR_EditorAlreadyExists {
            get {
                return ResourceManager.GetString("STR_EditorAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not remove owner from item..
        /// </summary>
        public static string STR_EditorCanNotBeRemoved {
            get {
                return ResourceManager.GetString("STR_EditorCanNotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have editor rights to that item..
        /// </summary>
        public static string STR_NoEditorRights {
            get {
                return ResourceManager.GetString("STR_NoEditorRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ObjectType} has been created successfully..
        /// </summary>
        public static string STR_ObjectCreated {
            get {
                return ResourceManager.GetString("STR_ObjectCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ObjectType} has been removed successfully..
        /// </summary>
        public static string STR_ObjectRemoved {
            get {
                return ResourceManager.GetString("STR_ObjectRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ObjectType} has been saved successfully..
        /// </summary>
        public static string STR_ObjectSaved {
            get {
                return ResourceManager.GetString("STR_ObjectSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a user first..
        /// </summary>
        public static string STR_SelectUserFirst {
            get {
                return ResourceManager.GetString("STR_SelectUserFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ObjectType} was unable to update..
        /// </summary>
        public static string STR_UnableToUpdate {
            get {
                return ResourceManager.GetString("STR_UnableToUpdate", resourceCulture);
            }
        }
    }
}
