//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRP.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaticValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRP.Core.Resources.StaticValues", typeof(StaticValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indexedControl.
        /// </summary>
        public static string Class_indexedControl {
            get {
                return ResourceManager.GetString("Class_indexedControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreditCard.
        /// </summary>
        public static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenId.
        /// </summary>
        public static string OpenId {
            get {
                return ResourceManager.GetString("OpenId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Shared/CheckView.ascx.
        /// </summary>
        public static string Partial_CheckView {
            get {
                return ResourceManager.GetString("Partial_CheckView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Shared/HelpForm.ascx.
        /// </summary>
        public static string Partial_HelpForm {
            get {
                return ResourceManager.GetString("Partial_HelpForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Shared/ItemBrowse.ascx.
        /// </summary>
        public static string Partial_ItemBrowse {
            get {
                return ResourceManager.GetString("Partial_ItemBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Shared/ItemForm.ascx.
        /// </summary>
        public static string Partial_ItemForm {
            get {
                return ResourceManager.GetString("Partial_ItemForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Shared/LogOnUserControl.ascx.
        /// </summary>
        public static string Partial_LogOnUserControl {
            get {
                return ResourceManager.GetString("Partial_LogOnUserControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Shared/PageHeader.ascx.
        /// </summary>
        public static string Partial_PageHeader {
            get {
                return ResourceManager.GetString("Partial_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Shared/QuestionForm.ascx.
        /// </summary>
        public static string Partial_QuestionForm {
            get {
                return ResourceManager.GetString("Partial_QuestionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Shared/TagView.ascx.
        /// </summary>
        public static string Partial_TagView {
            get {
                return ResourceManager.GetString("Partial_TagView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Shared/TransactionForm.ascx.
        /// </summary>
        public static string Partial_TransactionForm {
            get {
                return ResourceManager.GetString("Partial_TransactionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        public static string Question_AddressLine2 {
            get {
                return ResourceManager.GetString("Question_AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Question_City {
            get {
                return ResourceManager.GetString("Question_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Question_Email {
            get {
                return ResourceManager.GetString("Question_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Question_FirstName {
            get {
                return ResourceManager.GetString("Question_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Question_LastName {
            get {
                return ResourceManager.GetString("Question_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Question_PhoneNumber {
            get {
                return ResourceManager.GetString("Question_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string Question_State {
            get {
                return ResourceManager.GetString("Question_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string Question_StreetAddress {
            get {
                return ResourceManager.GetString("Question_StreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string Question_Zip {
            get {
                return ResourceManager.GetString("Question_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string QuestionSet_ContactInformation {
            get {
                return ResourceManager.GetString("QuestionSet_ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmountTotal.
        /// </summary>
        public static string Report_AmountTotal {
            get {
                return ResourceManager.GetString("Report_AmountTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks_Amount.
        /// </summary>
        public static string Report_Checks_Amount {
            get {
                return ResourceManager.GetString("Report_Checks_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks_CheckNumber.
        /// </summary>
        public static string Report_Checks_CheckNumber {
            get {
                return ResourceManager.GetString("Report_Checks_CheckNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks_DateReceived.
        /// </summary>
        public static string Report_Checks_DateReceived {
            get {
                return ResourceManager.GetString("Report_Checks_DateReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks_Notes.
        /// </summary>
        public static string Report_Checks_Notes {
            get {
                return ResourceManager.GetString("Report_Checks_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks_Payee.
        /// </summary>
        public static string Report_Checks_Payee {
            get {
                return ResourceManager.GetString("Report_Checks_Payee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks_TransactionId.
        /// </summary>
        public static string Report_Checks_TransactionId {
            get {
                return ResourceManager.GetString("Report_Checks_TransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DonationTotal.
        /// </summary>
        public static string Report_DonationTotal {
            get {
                return ResourceManager.GetString("Report_DonationTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Report_Paid {
            get {
                return ResourceManager.GetString("Report_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentType.
        /// </summary>
        public static string Report_PaymentType {
            get {
                return ResourceManager.GetString("Report_PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Report_Quantity {
            get {
                return ResourceManager.GetString("Report_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Report_Total {
            get {
                return ResourceManager.GetString("Report_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks.
        /// </summary>
        public static string Tab_Checks {
            get {
                return ResourceManager.GetString("Tab_Checks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupons.
        /// </summary>
        public static string Tab_Coupons {
            get {
                return ResourceManager.GetString("Tab_Coupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Tab_Details {
            get {
                return ResourceManager.GetString("Tab_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editors.
        /// </summary>
        public static string Tab_Editors {
            get {
                return ResourceManager.GetString("Tab_Editors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string Tab_Questions {
            get {
                return ResourceManager.GetString("Tab_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Tab_Reports {
            get {
                return ResourceManager.GetString("Tab_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string Tab_Templates {
            get {
                return ResourceManager.GetString("Tab_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string Tab_Transactions {
            get {
                return ResourceManager.GetString("Tab_Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMT.
        /// </summary>
        public static string Upay_Amount {
            get {
                return ResourceManager.GetString("Upay_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL_LINK.
        /// </summary>
        public static string Upay_CancelLink {
            get {
                return ResourceManager.GetString("Upay_CancelLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_LINK.
        /// </summary>
        public static string Upay_ErrorLink {
            get {
                return ResourceManager.GetString("Upay_ErrorLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPAY_SITE_ID.
        /// </summary>
        public static string Upay_SiteId {
            get {
                return ResourceManager.GetString("Upay_SiteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS_LINK.
        /// </summary>
        public static string Upay_SuccessLink {
            get {
                return ResourceManager.GetString("Upay_SuccessLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXT_TRANS_ID.
        /// </summary>
        public static string Upay_TransactionId {
            get {
                return ResourceManager.GetString("Upay_TransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALIDATION_KEY.
        /// </summary>
        public static string Upay_ValidationKey {
            get {
                return ResourceManager.GetString("Upay_ValidationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Shared/PageHeader.ascx.
        /// </summary>
        public static string View_PageHeader {
            get {
                return ResourceManager.GetString("View_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Shared/TemplateInstructions.ascx.
        /// </summary>
        public static string View_TemplateInstructions {
            get {
                return ResourceManager.GetString("View_TemplateInstructions", resourceCulture);
            }
        }
    }
}
